name: snakemake-seurat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.2
  - r-seurat=4.4.0
  - r-dplyr=1.1.3
  - r-ggplot2=3.5.0
  - r-patchwork=1.2.0
  - r-yaml=2.3.7
  - snakemake=7.32.4
  - r-optparse=1.7.3
